Razor/Pages/Shared/Uppgifter/FriendInput.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;
using Models.DTO;
using Services;

namespace Razor.Pages.Shared.Uppgifter
{
    public class FriendInputModel : PageModel
    {
        IFriendsService _service = null;
        ILogger<FriendInputModel> _logger = null;

        [BindProperty]
        public csFriendIM FriendIM { get; set; }

        public IFriend Friends { get; set; }

        public async Task<IActionResult> OnGet()
        {

            if (Guid.TryParse(Request.Query["id"], out Guid _id))
            {

                FriendIM = new csFriendIM(await _service.ReadFriendAsync(null, _id, false));
            }
            else
            {

                FriendIM = new csFriendIM();
                FriendIM.StatusIM = enStatusIM.Inserted;

            }
            return Page();
        }

        public async Task<IActionResult> OnPostSave()
        {
            if (FriendIM.StatusIM == enStatusIM.Inserted)
            {
                try
                {

                    var updatedModel = FriendIM.UpdateModel(new csFriend()
                    {
                        FriendId = Guid.Empty,
                        FirstName = FriendIM.FirstName,
                        LastName = FriendIM.LastName,
                        Email = FriendIM.Email,
                        Birthday = FriendIM.Birthday,
                        Address = new csAddress()
                        {
                            AddressId = Guid.Empty,
                            StreetAddress = FriendIM.StreetAddress,
                            ZipCode = FriendIM.ZipCode,
                            City = FriendIM.City,
                            Country = FriendIM.Country
                        },
                    });

                    var updatedAdress = await _service.CreateAddressAsync(null, new csAddressCUdto()
                    {
                        AddressId = updatedModel.Address.AddressId,
                        StreetAddress = updatedModel.Address.StreetAddress,
                        ZipCode = updatedModel.Address.ZipCode,
                        City = updatedModel.Address.City,
                        Country = updatedModel.Address.Country,
                    });

                    var updatedFriend = await _service.CreateFriendAsync(null, new csFriendCUdto()
                    {
                        FriendId = updatedModel.FriendId,
                        FirstName = updatedModel.FirstName,
                        LastName = updatedModel.LastName,
                        Email = updatedModel.Email,
                        Birthday = updatedModel.Birthday,
                        AddressId = updatedAdress.AddressId
                    });

                    return Redirect($"/Shared/Uppgifter/FriendView?id={updatedFriend.FriendId}");

                }
                catch (Exception ex)
                {
                    return StatusCode(500);
                }
            }
            else
            {
                try
                {

                    var updatedModel = FriendIM.UpdateModel(new csFriend()
                    {
                        FriendId = FriendIM.FriendId,
                        FirstName = FriendIM.FirstName,
                        LastName = FriendIM.LastName,
                        Email = FriendIM.Email,
                        Birthday = FriendIM.Birthday,
                        Address = new csAddress()
                        {
                            AddressId = FriendIM.AddressId,
                            StreetAddress = FriendIM.StreetAddress,
                            ZipCode = FriendIM.ZipCode,
                            City = FriendIM.City,
                            Country = FriendIM.Country
                        },
                    });

                    var updatedFriend = await _service.UpdateFriendAsync(null, new csFriendCUdto()
                    {
                        FriendId = updatedModel.FriendId,
                        FirstName = updatedModel.FirstName,
                        LastName = updatedModel.LastName,
                        Email = updatedModel.Email,
                        Birthday = updatedModel.Birthday,
                        AddressId = updatedModel.Address.AddressId,
                        PetsId = FriendIM.Pets,
                        QuotesId = FriendIM.Quotes,

                    });
                    var updatedAdress = await _service.UpdateAddressAsync(null, new csAddressCUdto()
                    {
                        AddressId = updatedModel.Address.AddressId,
                        StreetAddress = updatedModel.Address.StreetAddress,
                        ZipCode = updatedModel.Address.ZipCode,
                        City = updatedModel.Address.City,
                        Country = updatedModel.Address.Country
                    });
                    return Redirect($"/Shared/Uppgifter/FriendView?id={updatedFriend.FriendId}");
                }
                catch (Exception ex)
                {
                    return StatusCode(500);
                }
            }
        }

        public FriendInputModel(IFriendsService service, ILogger<FriendInputModel> logger)
        {
            _logger = logger;
            _service = service;
        }

        public enum enStatusIM { Unknown, Unchanged, Inserted, Modified, Deleted }
        public class csFriendIM
        {
            public enStatusIM StatusIM { get; set; }

            public Guid FriendId { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }

            public string Email { get; set; }
            public DateTime? Birthday { get; set; }

            public Guid AddressId { get; set; }
            public string StreetAddress { get; set; }
            public int ZipCode { get; set; }
            public string City { get; set; }
            public string Country { get; set; }

            public List<Guid> Pets { get; set; }
            public List<Guid> Quotes { get; set; }

            public csFriendIM() { StatusIM = enStatusIM.Unchanged; }

            public csFriendIM(csFriendIM original)
            {
                StatusIM = original.StatusIM;

                FriendId = original.FriendId;
                FirstName = original.FirstName;
                LastName = original.LastName;

                Email = original.Email;
                Birthday = original.Birthday;

                StreetAddress = original.StreetAddress;
                ZipCode = original.ZipCode;
                City = original.City;
                Country = original.Country;

                Pets = original.Pets;
                Quotes = original.Quotes;
            }

            public csFriendIM(IFriend model)
            {

                FriendId = model.FriendId;
                FirstName = model.FirstName;
                LastName = model.LastName;

                Email = model.Email;
                Birthday = model.Birthday;

                AddressId = model.Address.AddressId;
                StreetAddress = model.Address.StreetAddress;
                ZipCode = model.Address.ZipCode;
                City = model.Address.City;
                Country = model.Address.Country;

                Pets = model.Pets.Select(x => x.PetId).ToList();
                Quotes = model.Quotes.Select(x => x.QuoteId).ToList();
            }

            public csFriend UpdateModel(csFriend model)
            {
                model.FirstName = FirstName;
                model.LastName = LastName;

                model.Email = Email;
                model.Birthday = Birthday;

                model.Address.StreetAddress = StreetAddress;
                model.Address.ZipCode = ZipCode;
                model.Address.City = City;
                model.Address.Country = Country;

                return model;
            }
        }
    }
}

Razor/Pages/Shared/Uppgifter/FriendView.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;
using Services;

namespace Razor.Pages.Shared.Uppgifter
{
    public class FriendViewModel : PageModel
    {
        IFriendsService _service = null;
        ILogger<FriendViewModel> _logger = null;

        public Guid CurrentFriendId {  get; set; }
        public csFriend CurrentFriend {  get; set; }

        [BindProperty]
        public Guid PetId { get; set; }
        

        

        public async Task<IActionResult> OnGet()
        {
            if (Guid.TryParse(Request.Query["id"], out Guid _id)) 
            {  
                CurrentFriendId = _id;
                var friend = await _service.ReadFriendAsync(null, CurrentFriendId, false);

                

                csFriend _friend = new csFriend()
                {
                    FriendId = friend.FriendId,
                    FirstName = friend.FirstName,
                    LastName = friend.LastName,
                    Email = friend.Email,
                    Birthday = friend.Birthday,
                    Address = friend.Address,
                    Quotes = friend.Quotes,
                    Pets = friend.Pets,
                };
                CurrentFriend = _friend;

                
            }
            return Page();
        }

        public async Task<IActionResult> OnPostDeletePet()
        {
            string id = Request.Form["id"];
            _service.DeletePetAsync(null, PetId);

            return Redirect($"~/Shared/Uppgifter/FriendView?id={id}");
        }


        public FriendViewModel(IFriendsService service, ILogger<FriendViewModel> logger)
        {
            _logger = logger;
            _service = service;
        }
    }
}

Razor/Pages/Shared/Uppgifter/ListOfFriends.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;
using Services;

namespace Razor.Pages.Shared.Uppgifter
{
    public class ListOfFriendsModel : PageModel
    {
        IFriendsService _service = null;
        ILogger<ListOfFriendsModel> _logger = null;

        public List<IFriend> Friends { get; set; }
        public string currentCity { get; set; }
        [BindProperty]
        public Guid RemoveFriendId { get; set; }

        public async Task<IActionResult> OnGet()
        {
            string id = Request.Query["id"];
            currentCity = id;


            var friends = await _service.ReadFriendsAsync(null, true, false, "", 0, 1000);
            var createdFriends = await _service.ReadFriendsAsync(null, false, false, "", 0, 1000);

            var allFriends = friends.Concat(createdFriends);

            var allFriendsWithAdress = allFriends.Select(x => x)
                .Where(x => x.Address != null)
                .ToList();

            Friends = allFriendsWithAdress
                .Where(x => x.Address.City == currentCity)
                .ToList();

            return Page();
        }        

        public async Task<IActionResult> OnPostDelete()
        {
            string id = Request.Form["id"];
            await _service.DeleteFriendAsync(null, RemoveFriendId);
            return Redirect($"~/Shared/Uppgifter/ListOfFriends?id={id}");
        }

        public ListOfFriendsModel(IFriendsService service, ILogger<ListOfFriendsModel> logger)
        {
            _service = service;
            _logger = logger;
        }
    }
}

Razor/Pages/Shared/Uppgifter/QuoteInput.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;
using Services;

namespace Razor.Pages.Shared.Uppgifter
{
    public class QuoteInputModel : PageModel
    {
        IFriendsService _service = null;
        ILogger<QuoteInputModel> _logger = null;
        public List<string> Quotes { get; set; }
        [BindProperty]
        public csQuoteIM QuoteIM { get; set; }
        public string Author { get; set; }

        public async Task<IActionResult> OnGet()
        {
            if (Guid.TryParse(Request.Query["id"], out Guid id))
            {
                QuoteIM = new csQuoteIM(await _service.ReadQuoteAsync(null, id, false));
            }
            else
            {
                Guid.TryParse(Request.Query["id2"], out Guid id2);
                QuoteIM = new csQuoteIM();
                Quotes = new List<string>();

                var quotes = await _service.ReadQuotesAsync(null, true, false, "", 0, 1000);
                var distinctQuotes = quotes.Select(x => x.Quote).Distinct().ToList();

                csSeedGenerator rndName = new csSeedGenerator();
                Author = rndName.FullName.ToString();   

                var info = await _service.ReadFriendAsync(null, id2, false);
                var existingQuotes = info.Quotes.Select(x => x.Quote).ToList();
                    
                for (int i = 0; i < distinctQuotes.Count; i++)
                {
                    foreach (var Quote in existingQuotes)
                    {
                        if(Quote == distinctQuotes[i])
                        {
                            distinctQuotes.RemoveAt(i);
                        }
                    }
                }
                Quotes = distinctQuotes;
                QuoteIM.FriendId = id2;
                QuoteIM.StatusIM = enStatusIM.Inserted;
            }

            return Page();
        }

        public async Task<IActionResult> OnPostSubmit()
        {
            if (QuoteIM.StatusIM == enStatusIM.Inserted)
            {
                Quotes = new List<string>();

                var updateModel = QuoteIM.UpdateModel(new csQuote()
                {
                    Author = QuoteIM.Author,
                    Quote = QuoteIM.Quote,

                });
                var updatedDTO = await _service.CreateQuoteAsync(null, new Models.DTO.csQuoteCUdto()
                {
                    QuoteId = Guid.Empty,
                    Quote = updateModel.Quote,
                    Author = updateModel.Author,


                });
                var friend = await _service.ReadFriendAsync(null, QuoteIM.FriendId, false);

                var test = friend.Quotes.Select(x => x.QuoteId).ToList();
                test.Add(updatedDTO.QuoteId);

                var updateFriend = await _service.UpdateFriendAsync(null, new Models.DTO.csFriendCUdto()
                {
                    FriendId = friend.FriendId,
                    FirstName = friend.FirstName,
                    LastName = friend.LastName,
                    Email = friend.Email,
                    Birthday = friend.Birthday,

                    AddressId = friend.Address.AddressId,
                    PetsId = friend.Pets.Select(x => x.PetId).ToList(),
                    QuotesId = test
                });

                return Redirect($"/Shared/Uppgifter/FriendView?id={QuoteIM.FriendId}");
            }
            else
            {
                var updateModel = QuoteIM.UpdateModel(new csQuote()
                {
                    Author = QuoteIM.Author,
                    Quote = QuoteIM.Quote,
                });

                var updatedDTO = _service.UpdateQuoteAsync(null, new Models.DTO.csQuoteCUdto()
                {
                    QuoteId = QuoteIM.QuoteId,
                    Author = updateModel.Author,
                    Quote = updateModel.Quote

                });

                return Redirect($"/Shared/Uppgifter/FriendView?id={QuoteIM.FriendId}");
            }
        }


        public QuoteInputModel(IFriendsService service, ILogger<QuoteInputModel> logger)
        {
            _logger = logger;
            _service = service;
        }
        public enum enStatusIM { Unknown, Unchanged, Inserted, Modified, Deleted }

        public class csQuoteIM
        {
            public enStatusIM StatusIM { get; set; }

            public Guid QuoteId { get; set; }
            public string Quote { get; set; }
            public string Author { get; set; }
            public Guid FriendId { get; set; }

            public csQuoteIM() { StatusIM = enStatusIM.Unchanged; }

            public csQuoteIM(csQuoteIM original)
            {
                QuoteId = original.QuoteId;
                Quote = original.Quote;
                Author = original.Author;
                FriendId = original.FriendId;
            }

            public csQuoteIM(IQuote model)
            {
                QuoteId = model.QuoteId;
                Quote = model.Quote;
                Author = model.Author;
                FriendId = model.Friends.Select(f => f.FriendId).FirstOrDefault();
            }

            public csQuote UpdateModel(csQuote model)
            {
                Quote = model.Quote;
                Author = model.Author;

                return model;
            }
        }
    }
}

Razor/Pages/Shared/Uppgifter/FriendInput.cshtml
@page
@model Razor.Pages.Shared.Uppgifter.FriendInputModel
@{
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@attribute [IgnoreAntiforgeryToken]

<div class="container px-4 py-4" id="add-edit-friend">
    <h2 class="pb-2 border-bottom">Add or edit a friend's details</h2>
    <p>Fill in the details below to add a friend. Once you have added your friend you can edit the details of your fiend such as favorite quotes and pets.</p>

    <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
        <div class="col-md-7 col-lg-8">
            <form class="needs-validation" method="post" novalidate>

                <input asp-for="FriendIM.FriendId" value="@Model.FriendIM.FriendId" type="hidden" />
                <input asp-for="FriendIM.StatusIM" value="@Model.FriendIM.StatusIM" type="hidden" />
                <input asp-for="FriendIM.AddressId" value="@Model.FriendIM.AddressId" type="hidden" />


                @if (Model.FriendIM.Pets != null || Model.FriendIM.Quotes != null)
                {
                    @foreach (var item in Model.FriendIM.Pets)
                    {
                        <input asp-for="FriendIM.Pets" value="@item" type="hidden" />
                    }

                    @foreach (var item in Model.FriendIM.Quotes)
                    {
                        <input asp-for="FriendIM.Quotes" value="@item" type="hidden" />
                    }
                }

                <div class="row g-3">
                    <div class="col-sm-6">
                        <label for="firstName" class="form-label">First name</label>
                        <input type="text" class="form-control" asp-for="@Model.FriendIM.FirstName" id="firstName" placeholder="" value="@Model.FriendIM.FirstName" required>
                        <div class="invalid-feedback">
                            Valid first name is required
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <label for="lastName" class="form-label">Last name</label>
                        <input type="text" class="form-control" id="lastName" asp-for="@Model.FriendIM.LastName" placeholder="" value="@Model.FriendIM.LastName" required>
                        <div class="invalid-feedback">
                            Valid last name is required
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <label for="email" class="form-label">Email <span class="text-body-secondary">(Optional)</span></label>
                        <input type="email" class="form-control" id="email" asp-for="@Model.FriendIM.Email" value="@Model.FriendIM.Email">
                        <div class="invalid-feedback">
                            Please enter a valid email address
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <label for="birthday" class="form-label">Birthday <span class="text-body-secondary">(Optional)</span></label>
                        <input type="Birthday" class="form-control" id="birthday" asp-for="@Model.FriendIM.Birthday" value="@Model.FriendIM.Birthday">
                        <div class="invalid-feedback">
                            Please enter a valid birthday
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <label class="form-check-label" for="userHasAddress"></label>
                        <input class="form-check-input" type="checkbox" value="" id="userHasAddress">
                        I know the address
                    </div>

                    <div class="row g-3 visible">
                        <div class="col-12">
                            <label for="address" class="form-label">Address</label>
                            <input type="text" class="form-control" id="address" asp-for="@Model.FriendIM.StreetAddress" value="@Model.FriendIM.StreetAddress" required>
                            <div class="invalid-feedback">
                                Please enter a street address
                            </div>
                        </div>

                        <div class="col-md-3">
                            <label for="zip" class="form-label">Zip</label>
                            <input type="text" class="form-control" id="zip" asp-for="@Model.FriendIM.ZipCode" value="@Model.FriendIM.ZipCode" required>
                            <div class="invalid-feedback">
                                Please enter a zip code
                            </div>
                        </div>

                        <div class="col-md-4">
                            <label for="city" class="form-label">City</label>
                            <input type="text" class="form-control" id="city" asp-for="@Model.FriendIM.City" value="@Model.FriendIM.City" required>
                            <div class="invalid-feedback">
                                Please enter a city
                            </div>
                        </div>

                        <div class="col-md-5">
                            <label for="country" class="form-label">Country</label>
                            <input type="text" class="form-control" id="country" asp-for="@Model.FriendIM.Country" value="@Model.FriendIM.Country" required>
                            <div class="invalid-feedback">
                                Please enter a country
                            </div>
                        </div>
                    </div>
                </div>

                <button class="w-100 btn btn-primary btn-lg my-4" asp-page-handler="Save" type="submit">Save</button>
            </form>
        </div>
    </div>
</div>

Razor/Pages/Shared/Uppgifter/FriendView.cshtml
@page
@model Razor.Pages.Shared.Uppgifter.FriendViewModel
@{
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@attribute [IgnoreAntiforgeryToken]
<div class="container px-4 py-4" id="view-friend">
    <h2 class="pb-2 border-bottom">View details of a friend</h2>
    <p>Below you find all the details of my friend. You can also modify the pets my friend has and the quotes he/she likes.</p>

    <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
        <div class="col-md-7 col-lg-8">
            <form class="needs-validation" novalidate>
                <div class="row g-3">
                    <div class="col-sm-6">
                        <label for="firstName" class="form-label">First name</label>
                        <input type="text" class="form-control" id="firstName" value="@Model.CurrentFriend.FirstName" readonly>
                    </div>

                    <div class="col-sm-6">
                        <label for="lastName" class="form-label">Last name</label>
                        <input type="text" class="form-control" id="lastName" value="@Model.CurrentFriend.LastName" readonly>
                    </div>

                    <div class="col-sm-6">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" value="@Model.CurrentFriend.Email" readonly>
                    </div>
                    <div class="col-sm-6">
                        <label for="birthday" class="form-label">Birthday</label>
                        <input type="birthday" class="form-control" id="birthday" value="@Model.CurrentFriend.Birthday" readonly>
                    </div>

                    <div class="row g-3 visible">
                        <div class="col-12">
                            <label for="address" class="form-label">Address</label>
                            <input type="text" class="form-control" id="address" value="@Model.CurrentFriend.Address.StreetAddress" readonly>
                        </div>

                        <div class="col-md-3">
                            <label for="zip" class="form-label">Zip</label>
                            <input type="text" class="form-control" id="zip" value="@Model.CurrentFriend.Address.ZipCode" readonly>
                        </div>

                        <div class="col-md-4">
                            <label for="city" class="form-label">City</label>
                            <input type="text" class="form-control" id="city" value="@Model.CurrentFriend.Address.City" readonly>
                        </div>

                        <div class="col-md-5">
                            <label for="country" class="form-label">Country</label>
                            <input type="text" class="form-control" id="country" value="@Model.CurrentFriend.Address.Country" readonly>
                        </div>
                    </div>
                </div>

                <a href="~/Shared/Uppgifter/FriendInput?id=@Model.CurrentFriendId" class="w-100 btn btn-primary btn-lg my-4">Edit friend details</a>
            </form>
        </div>
        

        <div class="col-md-7 col-lg-8">
                <h3 class="pb-2">
                    My friend's pets
                <a href="~/Shared/Uppgifter/PetInputViewModel?id=create-pet&id2=@Model.CurrentFriendId" class="btn btn-success btn-sm" type="button">Add</a>
                </h3>
          @foreach(var item in Model.CurrentFriend.Pets)
          {
                <div class="row mb-2 text-center">
                    <div class="col-md-10 themed-grid-col">@item.Name The @item.Mood @item.Kind</div>
                    <div class="col-md-2 themed-grid-col">
                        <a href="~/Shared/Uppgifter/PetInputViewModel?id=@item.PetId" class="btn btn-secondary btn-sm" type="button">Edit</a>
                        <a href="#modals" class="btn btn-danger btn-sm" data-bs-toggle="modal"
                           data-bs-target="#deleteModal" delete-pet-id="@item.PetId" type="button">Delete</a>
                    </div>
                </div>
          } 
        </div>
       

        <div class="col-md-7 col-lg-8">
            <h3 class="pb-2">
                My friend's favorite quotes
                <a href="~/Shared/Uppgifter/QuoteInput?id=create-Quote&id2=@Model.CurrentFriendId" class="btn btn-success btn-sm" type="button">Add</a>
            </h3>

            @foreach(var item in Model.CurrentFriend.Quotes)
            {
                <div class="row mb-2 text-center">
                    <div class="col-md-10 themed-grid-col">
                        @item.Quote
                        <div class="col-md-16  text-end">@item.Author</div>
                    </div>
                    <div class="col-md-2 themed-grid-col">
                        <a href="~/Shared/Uppgifter/QuoteInput?id=@item.QuoteId" class="btn btn-secondary btn-sm" type="button">Edit</a>
                        <a href="#modals" class="btn btn-danger btn-sm" type="button">Delete</a>
                    </div>
                </div>
            }
            

        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this friend?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form method="post" asp-page-handler="DeletePet">
                    <input type="hidden" name="PetId" id="deletepetid" />
                    <input type="hidden" name="id" value="@Model.CurrentFriendId" />
                    <button type="submit" class="btn btn-danger" id="confirmDeleteButton">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    var deleteModal = document.getElementById('deleteModal');
    deleteModal.addEventListener('show.bs.modal', function (event) {
        var button = event.relatedTarget; // Button that triggered the modal
        var friendId = button.getAttribute('delete-pet-id'); // Extract info from data-* attributes
        var input = deleteModal.querySelector('#deletepetid');
        input.value = friendId; // Update the hidden input field with the friendId
    });
</script>

Razor/Pages/Shared/Uppgifter/FriendsByCity.cshtml
@page
@model Razor.Pages.Shared.Uppgifter.FriendsByCityModel
@{
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@attribute [IgnoreAntiforgeryToken]
<div class="container px-4 py-4" id="friends-in-a-country">
    <h2 class="pb-2 border-bottom">Friends in @Model.currentCountry</h2>
    <p>Click in on a city below to see my friends living in that city.</p>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 g-4 py-5">

        @for(int i = 0; i < Model.distinctCities.Count; i++)
        {
            <div class="col d-flex align-items-start">
                <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#backpack" /></svg>
                <div>
                    <h3 class="fw-bold mb-0 fs-4 text-body-emphasis">@Model.distinctCities[i].City</h3>
                    <p>@Model.infoAllDtos.Friends.Where(x => x.City == @Model.distinctCities[i].City).Select( x => x.NrFriends).Sum() friends and
                        @Model.infoAllDtos.Pets.Where(x => x.City == @Model.distinctCities[i].City).Select( x => x.NrPets).Sum() pets.
                    </p>
                    <a href="~/Shared/Uppgifter/ListOfFriends?id=@Model.distinctCities[i].City" class="btn btn-primary">
                        See friends
                    </a>
                </div>
            </div>
        }
    </div>
</div>