MVC/Models/FriendInputViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Models;

namespace MVC.Models
{
    public class FriendInputViewModel
    {
        [BindProperty]
        public csFriendIM FriendIM { get; set; }



        public enum enStatusIM { Unknown, Unchanged, Inserted, Modified, Deleted }
        public class csFriendIM
        {
            public enStatusIM StatusIM { get; set; }

            public Guid FriendId { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }

            public string Email { get; set; }
            public DateTime? Birthday { get; set; }

            public Guid AddressId { get; set; }
            public string StreetAddress { get; set; }
            public int ZipCode { get; set; }
            public string City { get; set; }
            public string Country { get; set; }

            public List<Guid> Pets { get; set; }
            public List<Guid> Quotes { get; set; }

            public csFriendIM() { StatusIM = enStatusIM.Unchanged; }

            public csFriendIM(csFriendIM original)
            {
                StatusIM = original.StatusIM;

                FriendId = original.FriendId;
                FirstName = original.FirstName;
                LastName = original.LastName;

                Email = original.Email;
                Birthday = original.Birthday;

                StreetAddress = original.StreetAddress;
                ZipCode = original.ZipCode;
                City = original.City;
                Country = original.Country;

                Pets = original.Pets;
                Quotes = original.Quotes;
            }

            public csFriendIM(IFriend model)
            {

                FriendId = model.FriendId;
                FirstName = model.FirstName;
                LastName = model.LastName;

                Email = model.Email;
                Birthday = model.Birthday;

                AddressId = model.Address.AddressId;
                StreetAddress = model.Address.StreetAddress;
                ZipCode = model.Address.ZipCode;
                City = model.Address.City;
                Country = model.Address.Country;

                Pets = model.Pets.Select(x => x.PetId).ToList();
                Quotes = model.Quotes.Select(q => q.QuoteId).ToList();
            }
        }
    }
}

MVC/Models/FriendViewModel.cs
using Azure.Core;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace MVC.Models
{
    public class FriendViewModel
    {
        public IFriend CurrentFriend { get; set; }

    }
}

MVC/Models/FriendsByCountryViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Models.DTO;
using Services;

namespace MVC.Models
{
	public class FriendsByCountryViewModel
	{

		public gstusrInfoAllDto infoAllDtos { get; set; }

		public List<string> distinctCountries { get; set; }


	}
}

MVC/Models/ListOfFriends.cs
using Azure.Core;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace MVC.Models
{
	public class ListOfFriends
	{
		public List<IFriend> Friends { get; set; }
		public string currentCity { get; set; }
		
	}
}

MVC/Models/PetInputViewModel.cs
using Azure.Core;
using Microsoft.AspNetCore.Mvc;
using Models;
using Models.DTO;

namespace MVC.Models
{
    public class PetInputViewModel
    {
        [BindProperty]
        public csPetIM PetIM { get; set; }

        public enum enStatusIM { Unknown, Unchanged, Inserted, Modified, Deleted }

        public class csPetIM
        {
            public enStatusIM StatusIM { get; set; }
            public Guid PetId { get; set; }
            public string Name { get; set; }
            public enAnimalKind Kind { get; set; }
            public enAnimalMood Mood { get; set; }
            public Guid FriendId { get; set; }

            public csPetIM() { StatusIM = enStatusIM.Unchanged; }

            public csPetIM(csPetIM original)
            {
                Name = original.Name;
                Kind = original.Kind;
                Mood = original.Mood;
                FriendId = original.FriendId;
            }

            public csPetIM(IPet model)
            {
                PetId = model.PetId;
                Name = model.Name;
                Kind = model.Kind;
                Mood = model.Mood;
                FriendId = model.Friend.FriendId;
            }
        }
    }
}

MVC/Models/QuoteInputViewModel.cs
using Azure.Core;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace MVC.Models
{
    public class QuoteInputViewModel
    {
        [BindProperty]
        public csQuoteIM QuoteIM { get; set; }
        public List<string> Quotes { get; set; }
        public string Author { get; set; }

        public enum enStatusIM { Unknown, Unchanged, Inserted, Modified, Deleted }
        public class csQuoteIM
        {
            public enStatusIM StatusIM { get; set; }

            public Guid QuoteId { get; set; }
            public string Quote { get; set; }
            public string Author { get; set; }
            public Guid FriendId { get; set; }

            public csQuoteIM() { StatusIM = enStatusIM.Unchanged; }

            public csQuoteIM(csQuoteIM original)
            {
                QuoteId = original.QuoteId;
                Quote = original.Quote;
                Author = original.Author;
                FriendId = original.FriendId;
            }

            public csQuoteIM(IQuote model)
            {
                QuoteId = model.QuoteId;
                Quote = model.Quote;
                Author = model.Author;
                FriendId = model.Friends.Select(f => f.FriendId).FirstOrDefault();
            }
        }
    }
}

MVC/Controllers/UppgifterController.cs
using Microsoft.AspNetCore.Mvc;
using Models;
using Models.DTO;
using MVC.Models;
using Services;

namespace MVC.Controllers
{
    public class UppgifterController : Controller
    {
        IFriendsService _service = null;
        ILogger<UppgifterController> _logger = null;

        public async Task<IActionResult> FriendsByCountry()
        {
            var info = await _service.InfoAsync;

            var clist = info.Friends.Select(x => x.Country).Where(x => x != null).Distinct().ToList();


            var vm = new FriendsByCountryViewModel() { infoAllDtos = info, distinctCountries = clist };

            return View("FriendsByCountry", vm);
        }

        public async Task<IActionResult> FriendsByCity(string id)
        {
            var info = await _service.InfoAsync;
            var cntrylist = info.Friends.Where(x => x.Country == id).ToList();

            var vm = new FriendsByCityVwM()
            {
                infoAllDtos = info,
                distinctCities = cntrylist.Where(x => x.City != null).Distinct().ToList(),
                currentCountry = id
            };

            return View(vm);
        }

        public async Task<IActionResult> ListOfFriends(string id)
        {
            var friends = await _service.ReadFriendsAsync(null, true, false, "", 0, 1000);
            var createdFriends = await _service.ReadFriendsAsync(null, false, false, "", 0, 1000);

            var allFriends = friends.Concat(createdFriends);

            var allFriendsWithAdress = allFriends
                .Select(x => x)
                .Where(x => x.Address != null)
                .ToList();
            var vm = new ListOfFriends()
            {
                currentCity = id,

                Friends = allFriendsWithAdress
                .Where(x => x.Address.City == id)
                .ToList()
            };

            return View(vm);
        }

        public async Task<IActionResult> FriendView(Guid id)
        {
            var vm = new FriendViewModel()
            {
                CurrentFriend = await _service.ReadFriendAsync(null, id, false)
            };

            return View(vm);
        }

        public async Task<IActionResult> FriendInput(Guid id)
        {
            if (id != Guid.Empty)
            {
                var vm = new FriendInputViewModel()
                {
                    FriendIM = new FriendInputViewModel.csFriendIM(await _service.ReadFriendAsync(null, id, false))
                };

                return View(vm);
            }
            else
            {

                var vm = new FriendInputViewModel()
                {
                    FriendIM = new FriendInputViewModel.csFriendIM(),

                };

                vm.FriendIM.StatusIM = FriendInputViewModel.enStatusIM.Inserted;

                return View(vm);
            }
        }

        [HttpPost]
        public async Task<IActionResult> FriendInputSave(FriendInputViewModel vm)
        {
            if (vm.FriendIM.StatusIM.Equals(FriendInputViewModel.enStatusIM.Inserted))
            {
                var createdAddress = await _service.CreateAddressAsync(null, new csAddressCUdto()
                {
                    AddressId = vm.FriendIM.AddressId,
                    StreetAddress = vm.FriendIM.StreetAddress,
                    ZipCode = vm.FriendIM.ZipCode,
                    City = vm.FriendIM.City,
                    Country = vm.FriendIM.Country,

                });
                var createdFriend = await _service.CreateFriendAsync(null, new csFriendCUdto()
                {
                    FriendId = vm.FriendIM.FriendId,
                    FirstName = vm.FriendIM.FirstName,
                    LastName = vm.FriendIM.LastName,
                    Email = vm.FriendIM.Email,
                    Birthday = vm.FriendIM.Birthday,
                    AddressId = createdAddress.AddressId,
                });

                return Redirect($"~/Uppgifter/FriendView?id={createdFriend.FriendId}");
            }
            else
            {
                var updatedFriend = await _service.UpdateFriendAsync(null, new csFriendCUdto()
                {
                    FriendId = vm.FriendIM.FriendId,
                    FirstName = vm.FriendIM.FirstName,
                    LastName = vm.FriendIM.LastName,
                    Email = vm.FriendIM.Email,
                    Birthday = vm.FriendIM.Birthday,
                    AddressId = vm.FriendIM.AddressId,
                    PetsId = vm.FriendIM.Pets,
                    QuotesId = vm.FriendIM.Quotes,
                });

                var updatedAddress = await _service.UpdateAddressAsync(null, new csAddressCUdto()
                {
                    AddressId = vm.FriendIM.AddressId,
                    StreetAddress = vm.FriendIM.StreetAddress,
                    ZipCode = vm.FriendIM.ZipCode,
                    City = vm.FriendIM.City,
                    Country = vm.FriendIM.Country,

                });

                return Redirect($"~/Uppgifter/FriendView?id={vm.FriendIM.FriendId}");
            }
        }

        
        public async Task<IActionResult> QuoteInput(Guid friendId, Guid quoteId)
        {
            if (quoteId != Guid.Empty)
            {

                var vm = new QuoteInputViewModel()
                {
                    QuoteIM = new QuoteInputViewModel.csQuoteIM(await _service.ReadQuoteAsync(null, quoteId, false)),
                };
                return View(vm);
            }
            else
            {
                var quotes = await _service.ReadQuotesAsync(null, true, false, "", 0, 1000);
                var distinctQuotes = quotes.Select(x => x.Quote).Distinct().ToList();

                csSeedGenerator rndName = new csSeedGenerator();

                var info = await _service.ReadFriendAsync(null, friendId, false);
                var existingQuotes = info.Quotes.Select(x => x.Quote).ToList();

                for (int i = 0; i < distinctQuotes.Count; i++)
                {
                    foreach (var Quote in existingQuotes)
                    {
                        if (Quote == distinctQuotes[i])
                        {
                            distinctQuotes.RemoveAt(i);
                        }
                    }
                }

                var vm = new QuoteInputViewModel()
                {
                    QuoteIM = new QuoteInputViewModel.csQuoteIM() { FriendId = friendId, StatusIM = QuoteInputViewModel.enStatusIM.Inserted},
                    Quotes = distinctQuotes,
                    Author = rndName.FullName.ToString(),
                };
                
                return View(vm);
            }  
        }

        [HttpPost]
        public async Task<IActionResult> OnPostSubmit(QuoteInputViewModel vm)
        {
            if (vm.QuoteIM.StatusIM.Equals(QuoteInputViewModel.enStatusIM.Inserted))
            {
                

                var createdQuoted = await _service.CreateQuoteAsync(null, new csQuoteCUdto()
                {
                    QuoteId = Guid.Empty,
                    Quote = vm.QuoteIM.Quote,
                    Author = vm.QuoteIM.Author


                });
                var friend = await _service.ReadFriendAsync(null, vm.QuoteIM.FriendId, false);

                var quoteList = friend.Quotes.Select(x => x.QuoteId).ToList();
                quoteList.Add(createdQuoted.QuoteId);

                var updateFriend = await _service.UpdateFriendAsync(null, new csFriendCUdto()
                {
                    FriendId = friend.FriendId,
                    FirstName = friend.FirstName,
                    LastName = friend.LastName,
                    Email = friend.Email,
                    Birthday = friend.Birthday,

                    AddressId = friend.Address.AddressId,
                    PetsId = friend.Pets.Select(x => x.PetId).ToList(),
                    QuotesId = quoteList
                });

                return Redirect($"/Uppgifter/FriendView?id={vm.QuoteIM.FriendId}");
            }
            else
            {
 

                var updatedDTO = _service.UpdateQuoteAsync(null, new csQuoteCUdto()
                {
                    QuoteId = vm.QuoteIM.QuoteId,
                    Author = vm.QuoteIM.Author,
                    Quote = vm.QuoteIM.Quote

                });

                return Redirect($"/Uppgifter/FriendView?id={vm.QuoteIM.FriendId}");
            }
        }

        public async Task<IActionResult> PetInput(Guid friendId, Guid petId)
        {
            if (petId != Guid.Empty)
            {
                var vm = new PetInputViewModel()
                {
                    PetIM = new PetInputViewModel.csPetIM(await _service.ReadPetAsync(null, petId, false))
                };

                return View(vm);
            }
            else
            {
                var vm = new PetInputViewModel()
                {
                    PetIM = new PetInputViewModel.csPetIM() { FriendId = friendId, StatusIM = PetInputViewModel.enStatusIM.Inserted }
                };
                return View(vm);
            }
        }

        public async Task<IActionResult> OnPostSave(PetInputViewModel vm)
        {
            if (vm.PetIM.StatusIM.Equals(PetInputViewModel.enStatusIM.Inserted))
            {

                await _service.CreatePetAsync(null, new csPetCUdto()
                {
                    PetId = vm.PetIM.PetId,
                    Name = vm.PetIM.Name,
                    Mood = vm.PetIM.Mood,
                    Kind = vm.PetIM.Kind,
                    FriendId = vm.PetIM.FriendId,
                });
                return Redirect($"/Uppgifter/FriendView?id={vm.PetIM.FriendId}");
            }
            else
            {

                var updatedDTO = await _service.UpdatePetAsync(null, new csPetCUdto()
                {

MVC/Views/Uppgifter/FriendInput.cshtml
@model FriendInputViewModel
@{
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@attribute [IgnoreAntiforgeryToken]

<div class="container px-4 py-4" id="add-edit-friend">
    <h2 class="pb-2 border-bottom">Add or edit a friend's details</h2>
    <p>Fill in the details below to add a friend. Once you have added your friend you can edit the details of your fiend such as favorite quotes and pets.</p>

    <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
        <div class="col-md-7 col-lg-8">
            <form class="needs-validation" method="post" novalidate>

                <input asp-for="FriendIM.FriendId" type="hidden" />
                <input asp-for="FriendIM.StatusIM" type="hidden" />
                <input asp-for="FriendIM.AddressId" type="hidden" />

                @if(Model.FriendIM.Pets != null || Model.FriendIM.Quotes != null)
                {
                    @foreach (var item in Model.FriendIM.Pets)
                    {
                        <input asp-for="FriendIM.Pets" value="@item" type="hidden" />
                    }

                    @foreach (var item in Model.FriendIM.Quotes)
                    {
                        <input asp-for="FriendIM.Quotes" value="@item" type="hidden" />
                    }
                }
                
              

                <div class="row g-3">
                    <div class="col-sm-6">
                        <label class="form-label">First name</label>
                        <input type="text" class="form-control" asp-for="FriendIM.FirstName" placeholder="">
                        <div class="invalid-feedback">
                            Valid first name is required
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <label for="lastName" class="form-label">Last name</label>
                        <input type="text" class="form-control" id="lastName" asp-for="FriendIM.LastName" placeholder="" required>
                        <div class="invalid-feedback">
                            Valid last name is required
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <label for="email" class="form-label">Email <span class="text-body-secondary">(Optional)</span></label>
                        <input type="email" class="form-control" id="email" asp-for="FriendIM.Email">
                        <div class="invalid-feedback">
                            Please enter a valid email address
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <label for="birthday" class="form-label">Birthday <span class="text-body-secondary">(Optional)</span></label>
                        <input type="Birthday" class="form-control" id="birthday" asp-for="FriendIM.Birthday">
                        <div class="invalid-feedback">
                            Please enter a valid birthday
                        </div>
                    </div>

                    <div class="row g-3 visible">
                        <div class="col-12">
                            <label for="address" class="form-label">Address</label>
                            <input type="text" class="form-control" id="address" asp-for="FriendIM.StreetAddress"required>
                            <div class="invalid-feedback">
                                Please enter a street address
                            </div>
                        </div>

                        <div class="col-md-3">
                            <label for="zip" class="form-label">Zip</label>
                            <input type="text" class="form-control" id="zip" asp-for="FriendIM.ZipCode"required>
                            <div class="invalid-feedback">
                                Please enter a zip code
                            </div>
                        </div>

                        <div class="col-md-4">
                            <label for="city" class="form-label">City</label>
                            <input type="text" class="form-control" id="city" asp-for="FriendIM.City" required>
                            <div class="invalid-feedback">
                                Please enter a city
                            </div>
                        </div>

                        <div class="col-md-5">
                            <label for="country" class="form-label">Country</label>
                            <input type="text" class="form-control" id="country" asp-for="FriendIM.Country" required>
                            <div class="invalid-feedback">
                                Please enter a country
                            </div>
                        </div>
                    </div>
                </div>

                <button asp-controller="Uppgifter" asp-action="FriendInputSave" class="w-100 btn btn-primary btn-lg my-4" type="submit">Save</button>
            </form>
        </div>
    </div>
</div>

MVC/Views/Uppgifter/FriendView.cshtml
@model FriendViewModel
@{
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@attribute [IgnoreAntiforgeryToken]
<div class="container px-4 py-4" id="view-friend">
    <h2 class="pb-2 border-bottom">View details of a friend</h2>
    <p>Below you find all the details of my friend. You can also modify the pets my friend has and the quotes he/she likes.</p>

    <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
        <div class="col-md-7 col-lg-8">
            <form class="needs-validation" novalidate>
                <div class="row g-3">
                    <div class="col-sm-6">
                        <label for="firstName" class="form-label">First name</label>
                        <input type="text" class="form-control" id="firstName" value="@Model.CurrentFriend.FirstName" readonly>
                    </div>

                    <div class="col-sm-6">
                        <label for="lastName" class="form-label">Last name</label>
                        <input type="text" class="form-control" id="lastName" value="@Model.CurrentFriend.LastName" readonly>
                    </div>

                    <div class="col-sm-6">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" value="@Model.CurrentFriend.Email" readonly>
                    </div>
                    <div class="col-sm-6">
                        <label for="birthday" class="form-label">Birthday</label>
                        <input type="birthday" class="form-control" id="birthday" value="@Model.CurrentFriend.Birthday" readonly>
                    </div>

                    <div class="row g-3 visible">
                        <div class="col-12">
                            <label for="address" class="form-label">Address</label>
                            <input type="text" class="form-control" id="address" value="@Model.CurrentFriend.Address.StreetAddress" readonly>
                        </div>

                        <div class="col-md-3">
                            <label for="zip" class="form-label">Zip</label>
                            <input type="text" class="form-control" id="zip" value="@Model.CurrentFriend.Address.ZipCode" readonly>
                        </div>

                        <div class="col-md-4">
                            <label for="city" class="form-label">City</label>
                            <input type="text" class="form-control" id="city" value="@Model.CurrentFriend.Address.City" readonly>
                        </div>

                        <div class="col-md-5">
                            <label for="country" class="form-label">Country</label>
                            <input type="text" class="form-control" id="country" value="@Model.CurrentFriend.Address.Country" readonly>
                        </div>
                    </div>
                </div>

                <a asp-controller="Uppgifter" asp-action="FriendInput" asp-route-id="@Model.CurrentFriend.FriendId" class="w-100 btn btn-primary btn-lg my-4">Edit friend details</a>
            </form>
        </div>


        <div class="col-md-7 col-lg-8">
            <h3 class="pb-2">
                My friend's pets
                <a asp-controller="Uppgifter" asp-action="PetInput" asp-route-friendId="@Model.CurrentFriend.FriendId" class="btn btn-success btn-sm" type="button">Add</a>
            </h3>
            @foreach (var item in Model.CurrentFriend.Pets)
            {
                <div class="row mb-2 text-center">
                    <div class="col-md-10 themed-grid-col">@item.Name The @item.Mood @item.Kind</div>
                    <div class="col-md-2 themed-grid-col">
                        <a asp-controller="Uppgifter" asp-action="PetInput" asp-route-petId="@item.PetId" class="btn btn-secondary btn-sm" type="button">Edit</a>
                        <a href="#modals" class="btn btn-danger btn-sm" type="button">Delete</a>
                    </div>
                </div>
            }
        </div>


        <div class="col-md-7 col-lg-8">
            <h3 class="pb-2">
                My friend's favorite quotes
                <a asp-controller="Uppgifter" asp-action="QuoteInput" asp-route-id="@Model.CurrentFriend.FriendId" class="btn btn-success btn-sm" type="button">Add</a>
            </h3>

            @foreach (var item in Model.CurrentFriend.Quotes)
            {
                <div class="row mb-2 text-center">
                    <div class="col-md-10 themed-grid-col">
                        @item.Quote
                        <div class="col-md-16  text-end">@item.Author</div>
                    </div>
                    <div class="col-md-2 themed-grid-col">
                        <a asp-controller="Uppgifter" asp-action="QuoteInput" asp-route-id2="@item.QuoteId" class="btn btn-secondary btn-sm" type="button">Edit</a>
                        <a href="#modals" class="btn btn-danger btn-sm" type="button">Delete</a>
                    </div>
                </div>
            }


        </div>
    </div>
</div>

MVC/Views/Uppgifter/FriendsByCity.cshtml
@model FriendsByCityVwM
@{
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@attribute [IgnoreAntiforgeryToken]
<div class="container px-4 py-4" id="friends-in-a-country">
    <h2 class="pb-2 border-bottom">Friends in @Model.currentCountry</h2>
    <p>Click in on a city below to see my friends living in that city.</p>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 g-4 py-5">

        @for (int i = 0; i < Model.distinctCities.Count; i++)
        {
            <div class="col d-flex align-items-start">
                <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#backpack" /></svg>
                <div>
                    <h3 class="fw-bold mb-0 fs-4 text-body-emphasis">@Model.distinctCities[i].City</h3>
                    <p>
                        @Model.infoAllDtos.Friends.Where(x => x.City == @Model.distinctCities[i].City).Select(x => x.NrFriends).Sum() friends and
                        @Model.infoAllDtos.Pets.Where(x => x.City == @Model.distinctCities[i].City).Select(x => x.NrPets).Sum() pets.
                    </p>
                    <a asp-controller="Uppgifter" asp-action="ListOfFriends" asp-route-id="@Model.distinctCities[i].City" class="btn btn-primary">
             
                        See friends
                    </a>
                </div>
            </div>
        }
    </div>
</div>

MVC/Views/Uppgifter/FriendsByCountry.cshtml
@model FriendsByCountryViewModel
@{
	ViewData["Title"] = "FriendsByCountry";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@attribute [IgnoreAntiforgeryToken]

<div class="container px-4 py-4" id="friends-by-country">
    <h2 class="pb-2 border-bottom">Friends by country</h2>
    <p>Click in on a country below to see what cities my friends are living in.</p>

    <div class="row row-cols-3 row-cols-lg-3,5 align-items-stretch g-4 py-5">

        @for (int i = 0; i < Model.distinctCountries.Count; i++)
        {
            <a asp-controller="Uppgifter" asp-action="FriendsByCity" asp-route-id="@Model.distinctCountries[i]" class="text-decoration-none">
                <div class="col">
                    <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg">
                        <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                            <h3 class="pt-1 mt-1 mb-4 display-6 lh-1 fw-bold">@Model.distinctCountries[i]</h3>
                            <p class="fs-5">
                                @Model.infoAllDtos.Friends.Where(x => x.Country == @Model.distinctCountries[i] && x.City == null).Select(x => x.NrFriends).Sum()
                                Friends in @Model.distinctCountries[i]
                            </p>
                        </div>
                    </div>
                </div>
            </a>
        }
    </div>
</div>

MVC/Views/Uppgifter/QuoteInput.cshtml
@model QuoteInputViewModel
@{
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@attribute [IgnoreAntiforgeryToken]

<div class="container px-4 py-4" id="list-of-quotes">
    <h2 class="pb-2 border-bottom">List of famous quotes</h2>

    <p>Pick a famous quote.</p>
    <form class="needs-validation" method="post" novalidate>


        
        <input asp-for="@Model.QuoteIM.StatusIM" value="@Model.QuoteIM.StatusIM" type="hidden" />
        <input asp-for="@Model.QuoteIM.QuoteId" value="@Model.QuoteIM.QuoteId" type="hidden" />
        <input asp-for="@Model.QuoteIM.FriendId" value="@Model.QuoteIM.FriendId" type="hidden" />

        @if (Model.QuoteIM.QuoteId != Guid.Empty)
        {
            <div class="row mb-2 text-center">
                <div class="col-md-10 themed-grid-col">
                    <label for="quoteId" class="form-label">Edit Quote</label>
                    <input asp-for="@Model.QuoteIM.Quote" type="text" class="form-control " id="petName" placeholder="" value="@Model.QuoteIM.Quote" required>
                </div>
                <div class="col-sm-10 themed-grid-col">
                    <label for="quoteId" class="form-label">Author</label>
                    <input asp-for="@Model.QuoteIM.Author" type="text" class="form-control " id="petName" placeholder="" value="@Model.QuoteIM.Author" required>s
                </div>

                <div class="col-md-10 themed-grid-col">

                    <button class="btn btn-success btn-sm" asp-controller="Uppgifter" asp-action="OnPostSubmit" type="submit">Submit</button>

                </div>
            </div>
        }
        else
        {
            <input asp-for="@Model.QuoteIM.Author" value="@Model.Author" type="hidden" />

            <div class="row mb-2 text-center">
                <div class="col-md-10 themed-grid-col">
                    <label for="quoteId" class="form-label">Dropdown Single Select</label>
                    <select asp-for="@Model.QuoteIM.Quote" class="form-select" id="quoteId">
                        @foreach (var item in Model.Quotes)
                        {
                            <option value="@item">@item</option>
                        }

                    </select>
                </div>
                <div class="col-md-2 themed-grid-col">

                    <button class="btn btn-success btn-sm" asp-controller="Uppgifter" asp-action="OnPostSubmit" type="submit">Submit</button>

                </div>
            </div>
        }

    </form>
</div>